// Generated by CoffeeScript 1.4.0
(function() {
  var BrowserDetection, Locale, LocaleModel, QueryString,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  QueryString = (function() {

    function QueryString() {}

    QueryString.get = function(name) {
      var regex, regexS, results;
      if (name) {
        name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
        regexS = "[\\?&]" + name + "=([^&#]*)";
        regex = new RegExp(regexS);
        results = regex.exec(window.location.search);
        if (results === null) {
          return "";
        } else {
          return decodeURIComponent(results[1].replace(/\+/g, " "));
        }
      } else {
        return "";
      }
    };

    return QueryString;

  }).call(this);

  LocaleModel = (function(_super) {

    __extends(LocaleModel, _super);

    function LocaleModel() {
      return LocaleModel.__super__.constructor.apply(this, arguments);
    }

    LocaleModel.prototype.defaults = {
      lang: null,
      strings: null
    };

    return LocaleModel;

  })(Backbone.Model);

  Locale = (function() {

    Locale.prototype.lang = null;

    Locale.prototype.data = null;

    function Locale() {
      this.get = __bind(this.get, this);
      this.loadBackup = __bind(this.loadBackup, this);
      this.onSuccess = __bind(this.onSuccess, this);      _.extend(this, Backbone.Events);
      this.lang = (navigator.language || navigator.userLanguage).toLowerCase();
      $.ajax({
        url: "/api/localisation/desktop/" + this.lang,
        dataType: "json",
        success: this.onSuccess,
        error: this.loadBackup
      });
      null;
    }

    Locale.prototype.onSuccess = function(event) {
      var d;
      d = null;
      if (event.responseText) {
        d = JSON.parse(event.responseText);
      } else {
        d = event;
      }
      this.data = new LocaleModel(d);
      this.trigger('complete');
      return null;
    };

    Locale.prototype.loadBackup = function() {
      var _this = this;
      $.ajax({
        url: '/locale/en/strings.txt',
        dataType: 'text',
        complete: this.onSuccess,
        error: function() {
          return console.log('error on loading backup');
        }
      });
      return null;
    };

    Locale.prototype.get = function(id) {
      return this.data.get('strings')[id] || "";
    };

    return Locale;

  })();

  BrowserDetection = (function() {

    BrowserDetection.prototype.browser = null;

    BrowserDetection.prototype.browserVersion = null;

    BrowserDetection.prototype.gl = null;

    BrowserDetection.prototype.webGL = false;

    BrowserDetection.prototype.webGLContext = false;

    BrowserDetection.prototype.webGLAdvanced = false;

    BrowserDetection.prototype.forcePass = false;

    function BrowserDetection() {
      this.testWebGLContext = __bind(this.testWebGLContext, this);
      this.onError = __bind(this.onError, this);
      this.onSuccess = __bind(this.onSuccess, this);
      this.compare = __bind(this.compare, this);      this.browser = BrowserDetect.browser;
      this.browserVersion = BrowserDetect.version;
      try {
        this.webGLContext = this.testWebGLContext();
        this.webGLAdvanced = this.testWebGLAdvancedFeats();
      } catch (error) {

      }
      this.webGL = Modernizr.webgl && this.webGLContext;
    }

    BrowserDetection.prototype.init = function() {
      return this.compare();
    };

    BrowserDetection.prototype.compare = function() {
      if ((this.browser === 'Chrome' && (this.webGL && this.webGLAdvanced)) || (this.forcePass === true)) {
        return this.onSuccess();
      } else if (this.browser === 'Chrome' && (this.webGL && !this.webGLAdvanced)) {
        return this.onError({
          message: 'Chrome_NoWebGLAdvancedFeats_message',
          buttons: ['Chrome_NoWebGL_button1', 'Chrome_NoWebGL_button2']
        });
      } else if (this.browser === 'Chrome' && !this.webGL) {
        return this.onError({
          message: 'Chrome_NoWebGL_message',
          buttons: ['Chrome_NoWebGL_button1', 'Chrome_NoWebGL_button2']
        });
      } else if (this.browser === 'Firefox' && (this.webGL && this.webGLAdvanced)) {
        return this.onError({
          message: 'FF4_Safari_WebGLmessage',
          buttons: ['FF4_Safari_WebGL_button1', 'FF4_Safari_WebGL_button2']
        });
      } else if (this.browser === 'Firefox' && (!this.webGL || !this.webGLAdvanced)) {
        return this.onError({
          message: 'FF4_noWebGL_message',
          buttons: ['FF4_noWebGL_button1', 'FF4_noWebGL_button2']
        });
      } else if (this.browser === 'Explorer' && (this.browserVersion === 6 || this.browserVersion === 7 || this.browserVersion === 8 || this.browserVersion === 9)) {
        return this.onError({
          message: 'Explorer_OldVersion_message',
          buttons: ['Explorer_OldVersion_button1']
        });
      } else if (this.browser === 'Safari' && (this.webGL && this.webGLAdvanced)) {
        return this.onError({
          message: 'FF4_Safari_WebGLmessage',
          buttons: ['FF4_Safari_WebGL_button1', 'FF4_Safari_WebGL_button2']
        });
      } else if (this.browser === 'Safari' && (!this.webGL || !this.webGLAdvanced)) {
        return this.onError({
          message: 'FF4_noWebGL_message',
          buttons: ['Safari_button1']
        });
      } else {
        if (!window.WebGLRenderingContext) {
          return this.onError({
            message: 'NoWebGLRenderingContext_message',
            buttons: ['NoWebGLRenderingContext_button1', 'NoWebGLRenderingContext_button2']
          });
        } else if (!this.webGLContext) {
          return this.onError({
            message: 'NoWebGL_message',
            buttons: ['NoWebGL_button1', 'NoWebGL_button2']
          });
        }
      }
    };

    BrowserDetection.prototype.onSuccess = function() {
      return this.onError({
        message: 'Chrome_NoWebGL_message',
        buttons: ['Chrome_NoWebGL_button1', 'Chrome_NoWebGL_button2']
      });
    };

    BrowserDetection.prototype.onError = function(error) {};

    BrowserDetection.prototype.testWebGLContext = function() {
      var result, _canvas;
      result = false;
      try {
        _canvas = document.createElement('canvas');
        if (!(this.gl = _canvas.getContext('experimental-webgl', {
          alpha: 1,
          premultipliedAlpha: true,
          antialias: false,
          stencil: true,
          preserveDrawingBuffer: false
        }))) {
          result = false;
        } else {
          result = true;
        }
      } catch (error) {
        result = false;
      }
      return result;
    };

    BrowserDetection.prototype.testWebGLAdvancedFeats = function() {
      var dxt1Supported, dxt1rgbaSupported, dxt3Supported, dxt5Supported, format, formats, _glExtensionCompressedTextureS3TC, _glExtensionTextureFilterAnisotropic, _i, _len;
      if (this.gl == null) {
        return false;
      }
      _glExtensionCompressedTextureS3TC = this.gl.getExtension('WEBGL_compressed_texture_s3tc') || this.gl.getExtension('MOZ_WEBGL_compressed_texture_s3tc') || this.gl.getExtension('WEBKIT_WEBGL_compressed_texture_s3tc');
      formats = this.gl.getParameter(this.gl.COMPRESSED_TEXTURE_FORMATS);
      dxt5Supported = false;
      dxt3Supported = false;
      dxt1Supported = false;
      dxt1rgbaSupported = false;
      if (formats != null) {
        for (_i = 0, _len = formats.length; _i < _len; _i++) {
          format = formats[_i];
          switch (format) {
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGBA_S3TC_DXT5_EXT:
              dxt5Supported = true;
              break;
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGB_S3TC_DXT1_EXT:
              dxt1Supported = true;
              break;
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGBA_S3TC_DXT1_EXT:
              dxt1rgbaSupported = true;
              break;
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGBA_S3TC_DXT3_EXT:
              dxt3Supported = true;
          }
        }
      }
      _glExtensionTextureFilterAnisotropic = this.gl.getExtension('EXT_texture_filter_anisotropic') || this.gl.getExtension('MOZ_EXT_texture_filter_anisotropic') || this.gl.getExtension('WEBKIT_EXT_texture_filter_anisotropic');
      return _glExtensionCompressedTextureS3TC && _glExtensionTextureFilterAnisotropic && dxt5Supported && dxt3Supported && dxt1Supported && dxt1rgbaSupported;
    };

    return BrowserDetection;

  })();

  $(function() {
    var img, img2,
      _this = this;
    window.error = {};
    window.detection = new BrowserDetection;
    window.detection.forcePass = QueryString.get("forcepass") === "on" ? true : false;
    window.errorMessage = {};
    window.detection.onSuccess = function() {
      $('#detect').remove();
      $('.qualityCheck').css({
        'display': 'table'
      });
      $('.qualityCheck').animate({
        opacity: 1
      }, 1000);
      if (navigator.appVersion.indexOf("Win") !== -1) {
        $('.qualityCheck').find('.settings_button').each(function(index, item) {
          return $(item).css({
            "padding": "7px 20px 8px 20px"
          });
        });
      }
      $('.low_quality').click(onLowClick);
      return $('.high_quality').click(onHighClick);
    };
    window.onQuality = function() {
      var script;
      script = document.createElement('script');
      script.type = 'text/javascript';
      script.src = '/js/r.js';
      return $("head").append(script);
    };
    window.onLowClick = function() {
      $('.qualityCheck').find('.settings_button').each(function(index, item) {
        $(item).css({
          'cursor': 'default'
        });
        return $(item).click(null);
      });
      (window || document).textureQuality = "low";
      (window || document).displayQuality = "med";
      (window || document).dof = false;
      return $('.qualityCheck').animate({
        opacity: 0
      }, 1000, window.onCompleteAnim);
    };
    window.onHighClick = function() {
      $('.qualityCheck').find('.settings_button').each(function(index, item) {
        $(item).css({
          'cursor': 'default'
        });
        return $(item).click(null);
      });
      (window || document).textureQuality = "med";
      (window || document).displayQuality = "hi";
      (window || document).dof = true;
      return $('.qualityCheck').animate({
        opacity: 0
      }, 1000, window.onCompleteAnim);
    };
    window.onCompleteAnim = function() {
      $('.qualityCheck').remove();
      $('#polite').css({
        'display': 'table'
      });
      return onQuality();
    };
    window.detection.onError = function(error) {
      window.errorMessage = error;
      window.error.locale = new Locale;
      return window.error.locale.on('complete', window.fallbackTemplate);
    };
    window.fallbackTemplate = function(error) {
      var b, button, c, _i, _len, _ref, _results;
      $('#detect').css({
        display: 'table'
      });
      $('#detect .title').html(window.error.locale.get('homeTitle'));
      $('#detect .errorMessage span').html(window.error.locale.get(window.errorMessage.message));
      window.addGAError();
      _ref = window.errorMessage.buttons;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        button = _ref[_i];
        if (window.showTechOrTrailer(button)) {
          c = window.error.locale.get(button + '_url');
          b = $('<a/>');
          b.css({
            'text-decoration': 'none'
          });
          if (button === "FF4_Safari_WebGL_button2") {
            b.click(window.tryAnyway);
          } else {
            b.attr({
              href: window.getHTML5RocksUrl(button, c),
              target: '_blank'
            });
          }
          b.html("<button class='abstractbutton'>" + (window.error.locale.get(button)) + "</button>");
          $('#detect .btnContainer').append(b);
          $('#detect .btnContainer').append("<br>");
          if (navigator.appVersion.indexOf("Win") !== -1) {
            _results.push($(b).css({
              "padding": "7px 20px 8px 20px"
            }));
          } else {
            _results.push(void 0);
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    window.addGAError = function() {
      return require(["http://google-analytics.com/ga.js"], function() {
        var pageTracker;
        pageTracker = _gat._getTracker("UA-37524215-3");
        return pageTracker._trackPageview('browser_error_page');
      });
    };
    window.getHTML5RocksUrl = function(label, url) {
      switch (label) {
        case "Chrome_NoWebGL_button2":
        case "FF4_noWebGL_button2":
        case "NoWebGLRenderingContext_button2":
        case "NoWebGL_button2":
          return 'http://www.html5rocks.com/tutorials/casestudies/oz/';
        case 'Chrome_NoWebGL_button1':
        case 'FF4_noWebGL_button1':
        case 'NoWebGLRenderingContext_button1':
        case 'NoWebGL_button1':
          return 'http://www.youtube.com/watch?v=VSyai9suXWc&feature=youtu.be';
        default:
          return url;
      }
    };
    window.showTechOrTrailer = function(label) {
      return true;
    };
    window.tryAnyway = function(event) {
      $('head').children().each(function(index, dom) {
        if (dom.src === "http://google-analytics.com/ga.js") {
          return $(dom).remove();
        }
      });
      event.preventDefault();
      return window.detection.onSuccess();
    };
    img = new Image();
    img.src = '/img/home/interface_1x.png';
    if (window.devicePixelRatio === 2) {
      img2 = new Image();
      img2.src = '/img/home/interface_2x.png';
    }
    return window.detection.init();
  });

}).call(this);
